language: java
jdk: oraclejdk8
notifications:
  email: false
  slack:
    secure: cAZP5ZuJhlAfexOaPcd/zk6i0jndjPVt4O7XfwFoZvO0LQ/QAVkk4BxvBMpL7HINfiD1oeye5VAGyH9xrfoO/I21uU01yrPUyVxRS3hDHttELbeDKYOCT8V1637EKO2udo3m+HzoXqOC6M8Hs4W62VEweKpNPbcrIcHjpwhHZAc=

env:
  global:
  - TERM=dumb

before_install: '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || openssl aes-256-cbc -K $encrypted_a4e14d5ba873_key -iv $encrypted_a4e14d5ba873_iv -in keystore.jks.enc -out keystore.jks -d'
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success: ./gradlew jacocoTestReport coveralls

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
- provider: script
  skip_cleanup: true
  script: ./gradlew curseforge -S
  on:
    all_branches: true
    repo: CyclopsMC/IntegratedDynamics
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: Aq1SUNmakwKghY9aqwJSDR4n2u6zAUe72HdJVazTK4cM14IcafeQp33TRsToyheE45Bmn8IiXwgKxn1wYgfCymRwRCLMNCmiu91pT1lDUzs8oIifwdqd/Ai6SuJekSp0VblZUw9igneMbVgIGmCxMVdjSLmWu4Bvs8sDNTOUyY4=
  on:
    all_branches: true
    repo: CyclopsMC/IntegratedDynamics
    tags: true
- provider: script
  skip_cleanup: true
  script: ./gradlew uploadArchives -S
  on:
    all_branches: true
    repo: CyclopsMC/IntegratedDynamics
    condition: $TRAVIS_BRANCH =~ ^(master|release|feature-).*$
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/docs/javadoc
  on:
    all_branches: true
    repo: CyclopsMC/IntegratedDynamics
    condition: "$TRAVIS_BRANCH =~ ^(master).*$"
